title: "Haejoon Lee"
bio: "PhD Candidate in Mechanical Engineering at the University of Michigan, Ann Arbor."
baseurl: "" 
url: "https://isagboola.github.io/isaiahagboola.github.io"
markdown: kramdown
theme: null

